package app.sensee.gradle

import kotlinx.serialization.json.Json
import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputDirectory
import org.gradle.api.tasks.Optional
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction

/**
 * Reads `*.json` files under [fixturesDir] and emits a single Kotlin source
 * file under [outputDir] containing a `@ContributesIntoSet @Inject` class that
 * implements `MockFixtureSet`. Relative file path (minus `.json`) becomes the
 * mock backend key.
 *
 * The JSON bytes are validated (parsed as `JsonElement`) and then embedded as
 * an escaped Kotlin string literal so the runtime value exactly matches what
 * is on disk — important for HTTP-mock equivalence.
 */
@CacheableTask
abstract class MockFixturesCodegenTask : DefaultTask() {
    @get:InputDirectory
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val fixturesDir: DirectoryProperty

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @get:Input
    abstract val packageName: Property<String>

    @get:Input
    abstract val className: Property<String>

    @get:Input
    @get:Optional
    abstract val classKdoc: Property<String>

    @TaskAction
    fun generate() {
        val root = fixturesDir.get().asFile
        if (!root.isDirectory) {
            throw GradleException("mockFixtures: input directory does not exist: $root")
        }

        val jsonFiles =
            root
                .walkTopDown()
                .filter { it.isFile && it.extension == "json" }
                .toList()
                .sortedBy { it.relativeTo(root).invariantSeparatorsPath }

        if (jsonFiles.isEmpty()) {
            throw GradleException("mockFixtures: no .json files under $root")
        }

        val entries =
            jsonFiles.map { file ->
                val relative = file.relativeTo(root).invariantSeparatorsPath
                val key = relative.removeSuffix(".json")
                val content = file.readText()
                runCatching { Json.parseToJsonElement(content) }
                    .onFailure { error ->
                        throw GradleException(
                            "mockFixtures: invalid JSON at $relative: ${error.message}",
                            error,
                        )
                    }
                key to content
            }

        val pkg = packageName.get()
        val cls = className.get()
        val kdoc = classKdoc.orNull
        val packageDir = outputDir.get().asFile.resolve(pkg.replace('.', '/'))
        packageDir.mkdirs()
        val outFile = packageDir.resolve("$cls.kt")

        val source =
            buildString {
                append("// Auto-generated by app.sensee.gradle.mock-fixtures. Do not edit.\n")
                append("@file:Suppress(\"ktlint\")\n")
                append("\n")
                append("package ").append(pkg).append("\n")
                append("\n")
                append("import app.sensee.core.mockBackend.MockFixtureSet\n")
                append("import dev.zacsweers.metro.AppScope\n")
                append("import dev.zacsweers.metro.ContributesIntoSet\n")
                append("import dev.zacsweers.metro.Inject\n")
                append("\n")
                if (!kdoc.isNullOrBlank()) {
                    append("/**\n")
                    kdoc.lines().forEach { line -> append(" * ").append(line).append("\n") }
                    append(" */\n")
                }
                append("@ContributesIntoSet(AppScope::class)\n")
                append("@Inject\n")
                append("public class ").append(cls).append(" : MockFixtureSet {\n")
                append("    override val fixtures: Map<String, String> = mapOf(\n")
                entries.forEach { (key, body) ->
                    append("        \"").append(key).append("\" to ")
                    append(body.toKotlinStringLiteral())
                    append(",\n")
                }
                append("    )\n")
                append("}\n")
            }

        outFile.writeText(source)
    }

    private fun String.toKotlinStringLiteral(): String =
        buildString(length + 2) {
            append('"')
            this@toKotlinStringLiteral.forEach { char ->
                when (char) {
                    '\\' -> append("\\\\")
                    '"' -> append("\\\"")
                    '$' -> {
                        append('\\')
                        append('$')
                    }
                    '\n' -> append("\\n")
                    '\r' -> append("\\r")
                    '\t' -> append("\\t")
                    '\b' -> append("\\b")
                    '\u000C' -> append("\\u000C")
                    else ->
                        if (char.code < CONTROL_CHAR_LIMIT) {
                            append("\\u")
                            append(char.code.toString(radix = 16).padStart(4, '0'))
                        } else {
                            append(char)
                        }
                }
            }
            append('"')
        }

    private companion object {
        const val CONTROL_CHAR_LIMIT = 0x20
    }
}
